UAuthGUIBranch and login merger
Devature/penguin-client pull request #41
Opened 2024-11-27 16:49 UTC by soot0-JoshR

This branch combines the UserAuthGUIBranch and login branches.

- added request to api for login
- moved email and password regex to a util file to be shared with front end registration
- added changes to GUI
- other changes to properly implement login
- added jwt to session storage

2024-11-27 21:43 UTC, nathanaelg16 requested changes

2024-11-27 21:43 UTC, nathanaelg16 commented on src/pages/SignIn.tsx
> +{/*const navigateToSignUp = useSignUpNavigation(); */}
We should try to keep our code as clean as possible and avoid having commented out code unless truly necessary.

2024-11-27 21:43 UTC, nathanaelg16 commented on src/pages/SignIn.tsx
> +            const response = await penguinApi.post('http://localhost:8080/api/v1/user/login',
`http://localhost:8080` should be removed from the URL since the base url will be injected through env variables.

2024-11-27 21:43 UTC, nathanaelg16 commented on src/pages/SignUp.tsx
> +    const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
Is this function in use? It should be removed. It seems a duplicate of `attemptSignUp`.

2024-11-27 21:43 UTC, nathanaelg16 commented on src/assets/penguins/penguin-icon-transparent-with-text-tall.svg
This logo seems to be cut off. Should this be removed?

2024-11-27 21:43 UTC, nathanaelg16 commented on src/assets/penguins/penguin-icon-white-with-text-tall.svg
This logo also appears cut off...

2024-11-27 21:43 UTC, nathanaelg16 commented on src/pages/SignIn.tsx
> +                        console.error("Bad Login credentials");
If the sign-in attempt is unsuccessful, we should communicate this to the user somehow instead of just logging it to console.

2024-11-27 21:43 UTC, nathanaelg16 commented on src/pages/SignUp.tsx
> +    const validateForm = () => {
I was able to register an account without having the passwords match. This function should probably check that the password fields match.

2024-11-27 22:24 UTC, soot0-JoshR commented on src/pages/SignIn.tsx
> +{/*const navigateToSignUp = useSignUpNavigation(); */}
Fixed.

2024-11-27 22:24 UTC, soot0-JoshR commented on src/pages/SignIn.tsx
> +            const response = await penguinApi.post('http://localhost:8080/api/v1/user/login',
Fixed.

2024-11-27 22:25 UTC, soot0-JoshR commented on src/pages/SignUp.tsx
> +    const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
Yes, but not for what that comment says it's being used for. Fixed.

2024-11-27 22:26 UTC, soot0-JoshR commented on src/assets/penguins/penguin-icon-transparent-with-text-tall.svg
I have no idea on the logo stuff. I can ask Aaron.

2024-11-27 22:50 UTC, soot0-JoshR commented on src/assets/penguins/penguin-icon-transparent-with-text-tall.svg
@Acohen455 Are we using these logos still?

2024-11-30 14:11 UTC, nathanaelg16 approved these changes, later dismissed
Changes look good to me. I tested on local and verified functionality. Some things were still not working right so I fixed them and pushed to the branch. I'm happy to merge this as it is.

2024-11-30 15:03 UTC, nathanaelg16 approved these changes, later dismissed
LGTM

2024-11-30 17:26 UTC, nathanaelg16 approved these changes

2024-11-30 17:26 UTC, merged